remote_theme: just-the-docs/just-the-docs
exclude:
  - w4/d5/socks/node_modules/
  - w4/d4/1-mongoose-intro/node_modules/
  - w7/d1/2-create-react-app/intro-to-cra/
  - w7/d3/pick-padd-poe/
  - w7/d3/valery-band-signup/
  - w7/d4/react-router/
  - w7/d5/react-connecting-to-backend/
